import React, { useState, useCallback, useMemo } from 'react';
import { XMarkIcon, SparklesIcon, CheckIcon, ArrowPathIcon } from '@heroicons/react/24/outline';
import { motion } from 'framer-motion';
import api from '../../services/api';

/** Styled checkbox — replaces the default browser input[type=checkbox] */
function Checkbox({ checked, onChange, onClick }) {
  return (
    <button
      type="button"
      role="checkbox"
      aria-checked={checked}
      onClick={onClick || onChange}
      className={`w-4.5 h-4.5 w-[18px] h-[18px] rounded-[5px] border-2 flex items-center justify-center shrink-0 transition-all duration-150 ${
        checked
          ? 'bg-primary border-primary shadow-sm shadow-primary/20'
          : 'bg-white border-gray-300 hover:border-primary/60'
      }`}
    >
      {checked && (
        <svg width="10" height="8" viewBox="0 0 10 8" fill="none">
          <path d="M1 4L3.5 6.5L9 1" stroke="white" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"/>
        </svg>
      )}
    </button>
  );
}

const CAT_COLORS = {
  endurance: '#3b82f6',
  lt1:       '#0ea5e9',
  tempo:     '#f97316',
  lt2:       '#8b5cf6',
  zone2:     '#22c55e',
  vo2max:    '#ef4444',
  hills:     '#f59e0b',
};

const CAT_LABELS = {
  endurance: 'Endurance',
  lt1:       'LT1',
  tempo:     'Tempo',
  lt2:       'LT2',
  zone2:     'Zone 2',
  vo2max:    'VO₂max',
  hills:     'Hills',
};

// SVG icon components matching TrainingForm
const CatSvg = ({ children, size = 12 }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor"
       strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{ flexShrink: 0, display: 'block' }}>
    {children}
  </svg>
);

const CAT_ICONS = {
  endurance: <CatSvg><path d="M2 12 C5.5 6 8.5 6 12 12 C15.5 18 18.5 18 22 12" /></CatSvg>,
  lt1: <CatSvg>
    <polyline points="3,19 9,16 14,10 20,5" />
    <circle cx="14" cy="10" r="2.2" fill="currentColor" stroke="none" />
  </CatSvg>,
  tempo: <CatSvg>
    <circle cx="12" cy="13" r="8" />
    <polyline points="12,9 12,13 15,15" />
    <line x1="9" y1="2" x2="15" y2="2" />
    <line x1="12" y1="2" x2="12" y2="5" />
  </CatSvg>,
  lt2: <CatSvg>
    <polyline points="3,19 7,18 10,15 13,9 19,4" />
    <circle cx="13" cy="9" r="2.2" fill="currentColor" stroke="none" />
  </CatSvg>,
  zone2: <CatSvg strokeWidth="1.8">
    <path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z" />
    <polyline points="8,12 10,10 11,14 13,10 14,12" strokeWidth="1.2" />
  </CatSvg>,
  vo2max: <CatSvg>
    <line x1="12" y1="19" x2="12" y2="5" />
    <polyline points="5,12 12,5 19,12" />
    <line x1="8" y1="19" x2="8" y2="16" strokeWidth="1.2" />
    <line x1="12" y1="21" x2="12" y2="19" strokeWidth="1.2" />
    <line x1="16" y1="19" x2="16" y2="16" strokeWidth="1.2" />
  </CatSvg>,
  hills: <CatSvg>
    <polyline points="2,20 7,10 11,15 15,8 19,13 22,20" />
    <line x1="2" y1="20" x2="22" y2="20" />
  </CatSvg>,
};

const SPORT_ICONS = { cycling: '/icon/bike.svg', running: '/icon/run.svg', swimming: '/icon/swim.svg' };

function CategoryPill({ category }) {
  if (!category) return <span className="text-gray-400 text-xs">—</span>;
  const color = CAT_COLORS[category] || '#6b7280';
  const icon = CAT_ICONS[category] || null;
  const label = CAT_LABELS[category] || category;
  return (
    <span
      className="inline-flex items-center gap-1 px-1.5 py-0.5 rounded text-[11px] font-semibold border"
      style={{ backgroundColor: `${color}22`, color, borderColor: `${color}55` }}
    >
      {icon} {label}
    </span>
  );
}

function formatDur(sec) {
  if (!sec) return '-';
  const h = Math.floor(sec / 3600);
  const m = Math.floor((sec % 3600) / 60);
  if (h > 0) return `${h}h${String(m).padStart(2, '0')}`;
  return `${m}'`;
}

export default function AutoClassifyModal({ onClose, onApplied }) {
  const [mode, setMode] = useState('classify'); // 'classify' | 'reset'

  // ── Classify state ────────────────────────────────────────
  const [sport, setSport] = useState('all');
  const [skipCategorized, setSkipCategorized] = useState(true);
  const [applyTitles, setApplyTitles] = useState(true);
  // When true, the server runs interval + dominant-zone classifiers only —
  // every title-keyword match is suppressed. Useful when the user's workout
  // titles are noisy (auto-generated by a head unit, generic "Morning Ride",
  // etc.) and the zone data is more trustworthy than the name.
  const [skipTitleDetection, setSkipTitleDetection] = useState(false);
  const [proposals, setProposals] = useState(null);
  const [selected, setSelected] = useState(new Set());
  const [loading, setLoading] = useState(false);
  const [applying, setApplying] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState(null);
  const [filterCat, setFilterCat] = useState('all');

  // ── Reset state ───────────────────────────────────────────
  const [resetSport, setResetSport] = useState('all');
  const [resetActivities, setResetActivities] = useState(null);
  const [resetSelected, setResetSelected] = useState(new Set());
  const [resetLoading, setResetLoading] = useState(false);
  const [resetting, setResetting] = useState(false);
  const [resetResult, setResetResult] = useState(null);
  const [resetError, setResetError] = useState(null);

  const loadResetActivities = useCallback(async () => {
    setResetLoading(true);
    setResetError(null);
    setResetActivities(null);
    setResetSelected(new Set());
    setResetResult(null);
    try {
      // Fetch all activities — including already categorized ones — so we can pick which to clear
      const { data } = await api.get('/api/integrations/strava/auto-classify', {
        params: { sport: resetSport, skipCategorized: 'false', limit: 1000 },
      });
      // Only show those that already have a category
      const categorized = (data.proposals || []).filter(p => p.currentCategory);
      setResetActivities(categorized);
      setResetSelected(new Set(categorized.map(p => p._id)));
    } catch (err) {
      setResetError(err.response?.data?.error || err.message);
    } finally {
      setResetLoading(false);
    }
  }, [resetSport]);

  const applyReset = useCallback(async () => {
    if (!resetActivities || resetSelected.size === 0) return;
    setResetting(true);
    setResetError(null);
    try {
      const items = resetActivities
        .filter(p => resetSelected.has(p._id))
        .map(p => ({ _id: p._id, category: null, applyCategory: true }));
      const { data } = await api.post('/api/integrations/strava/auto-classify/apply', { items });
      setResetResult(data.updated);
      if (onApplied) onApplied();
    } catch (err) {
      setResetError(err.response?.data?.error || err.message);
    } finally {
      setResetting(false);
    }
  }, [resetActivities, resetSelected, onApplied]);

  const allResetSelected = resetActivities?.length > 0 && resetActivities.every(p => resetSelected.has(p._id));
  const toggleAllReset = () => {
    if (allResetSelected) {
      setResetSelected(new Set());
    } else {
      setResetSelected(new Set(resetActivities.map(p => p._id)));
    }
  };

  const loadProposals = useCallback(async () => {
    setLoading(true);
    setError(null);
    setProposals(null);
    setSelected(new Set());
    setResult(null);
    try {
      const { data } = await api.get('/api/integrations/strava/auto-classify', {
        params: {
          sport,
          skipCategorized: skipCategorized ? 'true' : 'false',
          // When the user wants zones/laps only, tell the server to short-
          // circuit the title classifier entirely. Server reads this as a
          // query param and skips the title-keyword regex.
          skipTitle: skipTitleDetection ? 'true' : 'false',
          limit: 500,
        },
      });
      setProposals(data.proposals || []);
      setSelected(new Set(data.proposals.map(p => p._id)));
    } catch (err) {
      setError(err.response?.data?.error || err.message);
    } finally {
      setLoading(false);
    }
  }, [sport, skipCategorized, skipTitleDetection]);

  const visibleProposals = useMemo(() => {
    if (!proposals) return [];
    if (filterCat === 'all') return proposals;
    return proposals.filter(p => p.proposedCategory === filterCat);
  }, [proposals, filterCat]);

  const allVisibleSelected = visibleProposals.length > 0 && visibleProposals.every(p => selected.has(p._id));

  const toggleAll = () => {
    if (allVisibleSelected) {
      setSelected(prev => {
        const next = new Set(prev);
        visibleProposals.forEach(p => next.delete(p._id));
        return next;
      });
    } else {
      setSelected(prev => {
        const next = new Set(prev);
        visibleProposals.forEach(p => next.add(p._id));
        return next;
      });
    }
  };

  const applyChanges = useCallback(async () => {
    if (!proposals || selected.size === 0) return;
    setApplying(true);
    setError(null);
    try {
      const items = proposals
        .filter(p => selected.has(p._id))
        .map(p => ({
          _id: p._id,
          category: p.proposedCategory,
          title: p.proposedTitle,
          applyCategory: true,
          applyTitle: applyTitles,
        }));
      const { data } = await api.post('/api/integrations/strava/auto-classify/apply', { items });
      setResult(data.updated);
      if (onApplied) onApplied();
    } catch (err) {
      setError(err.response?.data?.error || err.message);
    } finally {
      setApplying(false);
    }
  }, [proposals, selected, applyTitles, onApplied]);

  // Category distribution for filter chips
  const catCounts = useMemo(() => {
    if (!proposals) return {};
    return proposals.reduce((acc, p) => {
      acc[p.proposedCategory] = (acc[p.proposedCategory] || 0) + 1;
      return acc;
    }, {});
  }, [proposals]);

  return (
    <motion.div
      initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
      className="fixed inset-0 z-50 flex items-end sm:items-center justify-center p-0 sm:p-6"
    >
      <div className="absolute inset-0 bg-black/50 backdrop-blur-sm" onClick={onClose} />
      <motion.div
        initial={{ y: '100%', opacity: 0 }} animate={{ y: 0, opacity: 1 }} exit={{ y: '100%', opacity: 0 }}
        transition={{ type: 'spring', damping: 30, stiffness: 300 }}
        className="relative bg-white rounded-t-2xl sm:rounded-2xl shadow-2xl w-full max-w-5xl flex flex-col overflow-hidden max-h-[88vh]">

        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-gray-100 shrink-0">
          <div className="flex items-center gap-4">
            <div className={`w-9 h-9 rounded-xl flex items-center justify-center ${mode === 'classify' ? 'bg-primary/10' : 'bg-red-50'}`}>
              {mode === 'classify'
                ? <SparklesIcon className="w-5 h-5 text-primary" />
                : <ArrowPathIcon className="w-5 h-5 text-red-500" />}
            </div>
            <div>
              <h2 className="text-base font-bold text-gray-900">
                {mode === 'classify' ? 'Auto-categorize Activities' : 'Reset Categories'}
              </h2>
              <p className="text-xs text-gray-400 mt-0.5">
                {mode === 'classify' ? 'Classify activities based on your training zones' : 'Remove categories from selected activities'}
              </p>
            </div>
            {/* Mode toggle */}
            <div className="flex items-center gap-0.5 ml-2 p-1 bg-gray-100 rounded-xl">
              <button
                onClick={() => setMode('classify')}
                className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold transition-all ${mode === 'classify' ? 'bg-white text-primary shadow-sm' : 'text-gray-500 hover:text-gray-700'}`}
              >
                <SparklesIcon className="w-3.5 h-3.5" /> Categorize
              </button>
              <button
                onClick={() => setMode('reset')}
                className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold transition-all ${mode === 'reset' ? 'bg-white text-red-500 shadow-sm' : 'text-gray-500 hover:text-gray-700'}`}
              >
                <ArrowPathIcon className="w-3.5 h-3.5" /> Reset
              </button>
            </div>
          </div>
          <button onClick={onClose} className="w-8 h-8 flex items-center justify-center rounded-xl hover:bg-gray-100 text-gray-400 transition-colors">
            <XMarkIcon className="w-5 h-5" />
          </button>
        </div>

        {/* Controls — classify mode */}
        <div className={`px-6 py-3.5 border-b border-gray-100 bg-gray-50/50 flex flex-wrap gap-3 items-center shrink-0 ${mode === 'reset' ? 'hidden' : ''}`}>
          <div>
            <label className="block text-[11px] text-gray-500 mb-1 font-medium">Sport</label>
            <div className="flex gap-1">
              {['all', 'cycling', 'running', 'swimming'].map(s => (
                <button
                  key={s}
                  onClick={() => setSport(s)}
                  className={`flex items-center gap-1 px-2.5 py-1 rounded-lg text-xs font-medium border transition-all ${
                    sport === s ? 'bg-primary text-white border-primary' : 'bg-white text-gray-500 border-gray-200 hover:bg-gray-50'
                  }`}
                >
                  {SPORT_ICONS[s] ? (
                    <img src={SPORT_ICONS[s]} className={`w-3.5 h-3.5 object-contain ${sport === s ? 'invert' : ''}`} alt="" />
                  ) : '🏅'}
                  {s === 'all' ? 'All' : s.charAt(0).toUpperCase() + s.slice(1)}
                </button>
              ))}
            </div>
          </div>

          <button type="button" onClick={() => setSkipCategorized(v => !v)} className="flex items-center gap-2 text-xs text-gray-600 cursor-pointer select-none">
            <Checkbox checked={skipCategorized} />
            Skip already categorized
          </button>

          <button type="button" onClick={() => setApplyTitles(v => !v)} className="flex items-center gap-2 text-xs text-gray-600 cursor-pointer select-none">
            <Checkbox checked={applyTitles} />
            Also set titles
          </button>

          {/* Zones-only mode — when on, the title-keyword classifier is
              skipped server-side and the proposal is based purely on
              interval zones and the dominant-zone fallback. Useful when
              activity names are auto-generated or otherwise noisy. */}
          <button
            type="button"
            onClick={() => setSkipTitleDetection(v => !v)}
            className="flex items-center gap-2 text-xs text-gray-600 cursor-pointer select-none"
            title="Ignore activity names — classify only from zone data in the laps"
          >
            <Checkbox checked={skipTitleDetection} />
            Use zones &amp; laps only (ignore titles)
          </button>

          <button
            onClick={loadProposals}
            disabled={loading}
            className="ml-auto flex items-center gap-1.5 px-3 py-1.5 bg-primary text-white text-xs font-semibold rounded-lg hover:bg-primary/90 disabled:opacity-50 transition-all"
          >
            {loading ? (
              <svg className="w-3.5 h-3.5 animate-spin" fill="none" viewBox="0 0 24 24">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/>
                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"/>
              </svg>
            ) : <SparklesIcon className="w-3.5 h-3.5" />}
            {loading ? 'Analyzing…' : 'Analyze'}
          </button>
        </div>

        {/* ── Reset controls ── */}
        {mode === 'reset' && (
          <div className="px-6 py-3.5 border-b border-gray-100 bg-red-50/30 flex flex-wrap gap-3 items-center shrink-0">
            <div>
              <label className="block text-[11px] text-gray-500 mb-1 font-medium">Sport</label>
              <div className="flex gap-1">
                {['all', 'cycling', 'running', 'swimming'].map(s => (
                  <button
                    key={s}
                    onClick={() => setResetSport(s)}
                    className={`flex items-center gap-1 px-2.5 py-1 rounded-lg text-xs font-medium border transition-all ${
                      resetSport === s ? 'bg-red-500 text-white border-red-500' : 'bg-white text-gray-500 border-gray-200 hover:bg-gray-50'
                    }`}
                  >
                    {SPORT_ICONS[s] ? (
                      <img src={SPORT_ICONS[s]} className={`w-3.5 h-3.5 object-contain ${resetSport === s ? 'invert' : ''}`} alt="" />
                    ) : '🏅'}
                    {s === 'all' ? 'All' : s.charAt(0).toUpperCase() + s.slice(1)}
                  </button>
                ))}
              </div>
            </div>
            <p className="text-xs text-gray-500 flex-1">
              Load activities that currently have a category assigned — then pick which ones to clear.
            </p>
            <button
              onClick={loadResetActivities}
              disabled={resetLoading}
              className="ml-auto flex items-center gap-1.5 px-3 py-1.5 bg-red-500 text-white text-xs font-semibold rounded-lg hover:bg-red-600 disabled:opacity-50 transition-all"
            >
              {resetLoading ? (
                <svg className="w-3.5 h-3.5 animate-spin" fill="none" viewBox="0 0 24 24">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/>
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"/>
                </svg>
              ) : <ArrowPathIcon className="w-3.5 h-3.5" />}
              {resetLoading ? 'Loading…' : 'Load categorized'}
            </button>
          </div>
        )}

        {/* Results — only scrollable when there is content */}
        <div className="overflow-y-auto">
          {/* ── Reset results ── */}
          {mode === 'reset' && (
            <>
              {resetError && (
                <div className="mx-6 mt-4 p-3 bg-red-50 border border-red-200 rounded-xl text-sm text-red-700">{resetError}</div>
              )}
              {resetResult !== null && (
                <div className="mx-6 mt-4 p-3 bg-emerald-50 border border-emerald-200 rounded-xl text-sm text-emerald-700 flex items-center gap-2">
                  <CheckIcon className="w-4 h-4" />
                  <strong>{resetResult}</strong> activities reset successfully!
                </div>
              )}
              {!resetActivities && !resetLoading && !resetError && (
                <div className="flex flex-col items-center justify-center py-10 px-6 text-center">
                  <div className="w-14 h-14 rounded-2xl bg-red-50 flex items-center justify-center mb-3">
                    <ArrowPathIcon className="w-7 h-7 text-red-300" />
                  </div>
                  <p className="text-sm font-medium text-gray-500">Click <strong className="text-gray-700">Load categorized</strong> to see activities that have a category assigned.</p>
                </div>
              )}
              {resetActivities && resetActivities.length === 0 && (
                <div className="text-center py-10 text-gray-400">
                  <ArrowPathIcon className="w-10 h-10 mx-auto mb-2 opacity-30" />
                  <p className="text-sm">No categorized activities found for the selected sport.</p>
                </div>
              )}
              {resetActivities && resetActivities.length > 0 && (
                <div className="px-5 pt-3 pb-2">
                  <div className="border border-gray-200 rounded-xl overflow-hidden">
                    <table className="w-full text-xs">
                      <thead>
                        <tr className="bg-gray-50 border-b border-gray-200">
                          <th className="px-3 py-2.5 text-left">
                            <Checkbox checked={allResetSelected} onClick={toggleAllReset} />
                          </th>
                          <th className="px-3 py-2.5 text-left font-semibold text-gray-500 text-[11px] uppercase tracking-wide w-28">Date</th>
                          <th className="px-2 py-2.5 text-left font-semibold text-gray-500 text-[11px] uppercase tracking-wide w-8"></th>
                          <th className="px-3 py-2.5 text-left font-semibold text-gray-500 text-[11px] uppercase tracking-wide">Activity name</th>
                          <th className="px-3 py-2.5 text-left font-semibold text-gray-500 text-[11px] uppercase tracking-wide w-24">Duration</th>
                          <th className="px-3 py-2.5 text-left font-semibold text-gray-500 text-[11px] uppercase tracking-wide w-32">Category</th>
                        </tr>
                      </thead>
                      <tbody>
                        {resetActivities.map((p, i) => {
                          const isSelected = resetSelected.has(p._id);
                          const date = p.startDate ? new Date(p.startDate).toLocaleDateString('cs-CZ', { day: '2-digit', month: '2-digit', year: '2-digit' }) : '-';
                          return (
                            <tr
                              key={p._id}
                              className={`border-b border-gray-100 cursor-pointer transition-colors ${isSelected ? 'bg-red-50/50' : 'hover:bg-gray-50'} ${i % 2 === 0 ? '' : 'bg-gray-50/30'}`}
                              onClick={() => setResetSelected(prev => {
                                const next = new Set(prev);
                                isSelected ? next.delete(p._id) : next.add(p._id);
                                return next;
                              })}
                            >
                              <td className="px-3 py-2.5">
                                <Checkbox checked={isSelected} onClick={e => { e.stopPropagation(); setResetSelected(prev => { const next = new Set(prev); isSelected ? next.delete(p._id) : next.add(p._id); return next; }); }} />
                              </td>
                              <td className="px-3 py-2.5 text-gray-400 whitespace-nowrap text-[11px]">{date}</td>
                              <td className="px-2 py-2.5">
                                {SPORT_ICONS[p.sport] ? (
                                  <img src={SPORT_ICONS[p.sport]} className="w-4 h-4 object-contain opacity-50" alt={p.sport} />
                                ) : <span className="text-gray-300">?</span>}
                              </td>
                              <td className="px-3 py-2.5 text-gray-700 max-w-xs truncate font-medium">{p.name}</td>
                              <td className="px-3 py-2.5 text-gray-400 text-[11px]">{formatDur(p.movingTime)}</td>
                              <td className="px-3 py-2.5">
                                <CategoryPill category={p.currentCategory} />
                              </td>
                            </tr>
                          );
                        })}
                      </tbody>
                    </table>
                  </div>
                </div>
              )}
            </>
          )}

          {/* ── Classify results ── */}
          {mode === 'classify' && <>
          {error && (
            <div className="mx-6 mt-4 p-3 bg-red-50 border border-red-200 rounded-xl text-sm text-red-700">{error}</div>
          )}

          {result !== null && (
            <div className="mx-6 mt-4 p-3 bg-emerald-50 border border-emerald-200 rounded-xl text-sm text-emerald-700 flex items-center gap-2">
              <CheckIcon className="w-4 h-4" />
              <strong>{result}</strong> activities updated successfully!
            </div>
          )}

          {!proposals && !loading && !error && (
            <div className="flex flex-col items-center justify-center py-10 px-6 text-center">
              <div className="w-14 h-14 rounded-2xl bg-primary/8 flex items-center justify-center mb-3">
                <SparklesIcon className="w-7 h-7 text-primary/50" />
              </div>
              <p className="text-sm font-medium text-gray-500">Choose a sport filter and click <strong className="text-gray-700">Analyze</strong> to get category suggestions based on your training zones.</p>
            </div>
          )}

          {proposals && proposals.length === 0 && (
            <div className="text-center py-10 text-gray-400">
              <SparklesIcon className="w-10 h-10 mx-auto mb-2 opacity-30" />
              <p className="text-sm">No activities to classify. Make sure your zones are configured in Profile.</p>
            </div>
          )}

          {proposals && proposals.length > 0 && (
            <div className="px-6 pt-4 pb-2">
              {/* Category filter chips */}
              <div className="flex flex-wrap gap-1.5 mb-3">
                <button
                  onClick={() => setFilterCat('all')}
                  className={`px-2.5 py-1 rounded-lg text-xs font-medium border transition-all ${filterCat === 'all' ? 'bg-gray-800 text-white border-gray-800' : 'bg-white text-gray-500 border-gray-200'}`}
                >
                  All ({proposals.length})
                </button>
                {Object.entries(catCounts).sort((a,b) => b[1]-a[1]).map(([cat, count]) => {
                  const color = CAT_COLORS[cat] || '#6b7280';
                  const icon = CAT_ICONS[cat] || null;
                  const label = CAT_LABELS[cat] || cat;
                  return (
                    <button
                      key={cat}
                      onClick={() => setFilterCat(filterCat === cat ? 'all' : cat)}
                      className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-lg text-xs font-semibold border transition-all"
                      style={filterCat === cat
                        ? { backgroundColor: color, color: '#fff', borderColor: color }
                        : { backgroundColor: `${color}18`, color, borderColor: `${color}44` }
                      }
                    >
                      {icon} {label} ({count})
                    </button>
                  );
                })}
              </div>

              {/* Table */}
              <div className="border border-gray-200 rounded-xl overflow-hidden">
                <table className="w-full text-xs">
                  <thead>
                    <tr className="bg-gray-50 border-b border-gray-200">
                      <th className="px-3 py-2.5 text-left">
                        <Checkbox checked={allVisibleSelected} onClick={toggleAll} />
                      </th>
                      <th className="px-3 py-2.5 text-left font-semibold text-gray-500 text-[11px] uppercase tracking-wide w-28">Date</th>
                      <th className="px-2 py-2.5 text-left w-8"></th>
                      <th className="px-3 py-2.5 text-left font-semibold text-gray-500 text-[11px] uppercase tracking-wide">Activity name</th>
                      <th className="px-3 py-2.5 text-left font-semibold text-gray-500 text-[11px] uppercase tracking-wide w-24">Duration</th>
                      <th className="px-3 py-2.5 text-left font-semibold text-gray-500 text-[11px] uppercase tracking-wide w-32">Category</th>
                      <th className="px-3 py-2.5 text-left font-semibold text-gray-500 text-[11px] uppercase tracking-wide">Proposed title</th>
                    </tr>
                  </thead>
                  <tbody>
                    {visibleProposals.map((p, i) => {
                      const isSelected = selected.has(p._id);
                      const date = p.startDate ? new Date(p.startDate).toLocaleDateString('cs-CZ', { day: '2-digit', month: '2-digit', year: '2-digit' }) : '-';
                      return (
                        <tr
                          key={p._id}
                          className={`border-b border-gray-100 cursor-pointer transition-colors ${isSelected ? 'bg-primary/5' : 'hover:bg-gray-50'}`}
                          onClick={() => setSelected(prev => {
                            const next = new Set(prev);
                            isSelected ? next.delete(p._id) : next.add(p._id);
                            return next;
                          })}
                        >
                          <td className="px-3 py-2.5">
                            <Checkbox checked={isSelected} onClick={e => { e.stopPropagation(); setSelected(prev => { const next = new Set(prev); isSelected ? next.delete(p._id) : next.add(p._id); return next; }); }} />
                          </td>
                          <td className="px-3 py-2.5 text-gray-400 whitespace-nowrap text-[11px]">{date}</td>
                          <td className="px-2 py-2.5">
                            {SPORT_ICONS[p.sport] ? (
                              <img src={SPORT_ICONS[p.sport]} className="w-4 h-4 object-contain opacity-50" alt={p.sport} />
                            ) : <span className="text-gray-300">?</span>}
                          </td>
                          <td className="px-3 py-2.5 text-gray-700 font-medium max-w-xs truncate">{p.name}</td>
                          <td className="px-3 py-2.5 text-gray-400 text-[11px]">{formatDur(p.movingTime)}</td>
                          <td className="px-3 py-2.5">
                            <div className="flex flex-col gap-1">
                              <CategoryPill category={p.proposedCategory} />
                              {/* Reason chip — explains WHY we proposed this
                                  category. Title matches feel high-confidence
                                  (user explicitly named the workout), interval
                                  evidence feels medium (data-driven), and the
                                  silent fallback gets no chip so the user can
                                  spot ambiguous proposals. */}
                              {p.titleMatch?.keyword && (
                                <span
                                  className="inline-flex items-center gap-1 px-1.5 py-0.5 rounded-full text-[10px] font-medium bg-primary/10 text-primary"
                                  title={`Matched the keyword "${p.titleMatch.keyword}" in the activity name`}
                                >
                                  🏷 from name: {p.titleMatch.keyword}
                                </span>
                              )}
                              {!p.titleMatch && p.intervalEvidence?.considered > 0 && (() => {
                                const ev = p.intervalEvidence;
                                const counts = [];
                                if (ev.vo2max > 0) counts.push(`${ev.vo2max} VO₂`);
                                if (ev.lt2 > 0) counts.push(`${ev.lt2} LT2`);
                                if (ev.lt1 > 0) counts.push(`${ev.lt1} LT1`);
                                const label = counts.length
                                  ? counts.join(' · ')
                                  : `${ev.considered} laps analysed`;
                                return (
                                  <span
                                    className="inline-flex items-center gap-1 px-1.5 py-0.5 rounded-full text-[10px] font-medium bg-blue-50 text-blue-700"
                                    title={`Based on ${ev.considered} work lap${ev.considered === 1 ? '' : 's'}`}
                                  >
                                    📊 {label}
                                  </span>
                                );
                              })()}
                              {/* Lap-typing preview — only present for structured
                                  categories (vo2max / lt2 / lt1 / tempo). Tells
                                  the user the apply pass will also tag intervals
                                  as work/recovery/etc, not just set the category. */}
                              {p.proposedLapTypes && (() => {
                                const lt = p.proposedLapTypes;
                                const total = (lt.work || 0) + (lt.recovery || 0) + (lt.warmup || 0) + (lt.cooldown || 0);
                                if (total === 0) return null;
                                const parts = [];
                                if (lt.work)     parts.push(`${lt.work} work`);
                                if (lt.recovery) parts.push(`${lt.recovery} rec`);
                                if (lt.warmup)   parts.push(`WU`);
                                if (lt.cooldown) parts.push(`CD`);
                                return (
                                  <span
                                    className="inline-flex items-center gap-1 px-1.5 py-0.5 rounded-full text-[10px] font-medium bg-emerald-50 text-emerald-700"
                                    title={`Will tag ${total} laps with their interval type when applied`}
                                  >
                                    🏃 {parts.join(' · ')}
                                  </span>
                                );
                              })()}
                            </div>
                          </td>
                          <td className="px-3 py-2.5 text-gray-600 text-[11px]">
                            {p.proposedTitle || <span className="text-gray-300">—</span>}
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            </div>
          )}
          </>}
        </div>

        {/* Footer — classify mode */}
        {mode === 'classify' && proposals && proposals.length > 0 && (
          <div className="px-6 py-4 border-t border-gray-100 bg-gray-50/50 flex items-center justify-between gap-3 shrink-0">
            <span className="text-xs text-gray-500">
              <strong className="text-gray-800">{selected.size}</strong> / {proposals.length} selected
              {!applyTitles && <span className="ml-2 text-gray-400">(titles won't be changed)</span>}
            </span>
            <div className="flex gap-2">
              <button onClick={onClose} className="px-3 py-1.5 text-xs text-gray-600 border border-gray-200 rounded-lg hover:bg-gray-100 transition-all">
                Cancel
              </button>
              <button
                onClick={applyChanges}
                disabled={applying || selected.size === 0}
                className="flex items-center gap-1.5 px-4 py-1.5 bg-primary text-white text-xs font-semibold rounded-lg hover:bg-primary/90 disabled:opacity-50 transition-all"
              >
                {applying ? (
                  <svg className="w-3.5 h-3.5 animate-spin" fill="none" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/>
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"/>
                  </svg>
                ) : <CheckIcon className="w-3.5 h-3.5" />}
                {applying ? 'Applying…' : `Apply to ${selected.size} activities`}
              </button>
            </div>
          </div>
        )}

        {/* Footer — reset mode */}
        {mode === 'reset' && resetActivities && resetActivities.length > 0 && (
          <div className="px-6 py-4 border-t border-red-100 bg-red-50/30 flex items-center justify-between gap-3 shrink-0">
            <span className="text-xs text-gray-500">
              <strong className="text-gray-800">{resetSelected.size}</strong> / {resetActivities.length} selected to reset
            </span>
            <div className="flex gap-2">
              <button onClick={onClose} className="px-3 py-1.5 text-xs text-gray-600 border border-gray-200 rounded-lg hover:bg-gray-100 transition-all">
                Cancel
              </button>
              <button
                onClick={applyReset}
                disabled={resetting || resetSelected.size === 0}
                className="flex items-center gap-1.5 px-4 py-1.5 bg-red-500 text-white text-xs font-semibold rounded-lg hover:bg-red-600 disabled:opacity-50 transition-all"
              >
                {resetting ? (
                  <svg className="w-3.5 h-3.5 animate-spin" fill="none" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/>
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"/>
                  </svg>
                ) : <ArrowPathIcon className="w-3.5 h-3.5" />}
                {resetting ? 'Resetting…' : `Reset ${resetSelected.size} activities`}
              </button>
            </div>
          </div>
        )}
      </motion.div>
    </motion.div>
  );
}
