/**
 * What's New — slide content + media paths.
 *
 * Videa nahraj do: client/public/videos/whats-new/<videoId>.mp4
 * Po nahrání nastav příslušný klíč v WHATS_NEW_VIDEOS_READY na true.
 *
 * Dokumentace natáčení: client/public/videos/whats-new/NATOČENÍ.md
 */
import {
  CalendarDaysIcon,
  PlayCircleIcon,
  BeakerIcon,
  PaintBrushIcon,
  BoltIcon,
  ArrowTrendingUpIcon,
  ChartBarSquareIcon,
  HeartIcon,
  CloudArrowDownIcon,
  PresentationChartLineIcon,
  SignalIcon,
  AdjustmentsHorizontalIcon,
  UsersIcon,
  DevicePhoneMobileIcon,
} from '@heroicons/react/24/outline';

export const RELEASE_TAG = '2026-06';

export const WHATS_NEW_VIDEO_DIR = '/videos/whats-new';

/**
 * Po nahrání souboru `<videoId>.mp4` do public/videos/whats-new/
 * změň hodnotu na true — modal automaticky přehraje video místo screenshotu.
 */
export const WHATS_NEW_VIDEOS_READY = {
  '01-strava-connect': false,
  '02-import-categorize': false,
  '03-analyze-workout': true,
  '04-power-profile': false,
  '05-lactate-curve': false,
  '06-training-zones': false,
  '07-plan-workout': false,
  '08-live-workout': false,
  '09-lactate-interval': false,
  '10-form-fitness': false,
  '11-compare-tests': false,
  '12-pdf-branding': false,
  '13-coach-squad': false,
  '14-ios-app': false,
};

export function whatsNewVideoUrl(videoId) {
  if (!videoId || !WHATS_NEW_VIDEOS_READY[videoId]) return null;
  return `${WHATS_NEW_VIDEO_DIR}/${videoId}.mp4`;
}

const RAW_SLIDES = [
  {
    id: 'strava-connect',
    icon: CloudArrowDownIcon,
    label: 'Integrations',
    title: 'Connect Strava in one click',
    body: 'Link your Strava account and LaChart pulls every ride, run and swim automatically — power, heart rate, pace, laps and elevation included.',
    bullets: [
      'Full history import on first connect',
      'New activities sync in the background',
      'Works alongside FIT uploads and manual logs',
    ],
    videoId: '01-strava-connect',
    image: '/images/training-calendar-960.webp',
    mediaCaption: 'Activities land straight in your training calendar',
    cta: 'Connect Strava',
    href: '/settings?tab=integrations',
    accent: '#fc4c02',
    stravaOnly: true,
  },
  {
    id: 'import-categorize',
    icon: BoltIcon,
    label: 'Import',
    title: 'Import & auto-categorize activities',
    body: 'Drop a FIT file or sync from Strava — LaChart reads interval structure, power zones and session title to tag every workout as endurance, threshold, VO₂max or recovery.',
    bullets: [
      'Smart category from interval blocks',
      'Bulk re-process a whole month of rides',
      'Manual override any time in the calendar',
    ],
    videoId: '02-import-categorize',
    image: '/screenshots/training-page-960.webp',
    mediaCaption: 'Every session sorted without manual tagging',
    cta: 'Set up sync',
    href: '/settings?tab=integrations',
    accent: '#6366f1',
  },
  {
    id: 'analyze-workout',
    icon: PresentationChartLineIcon,
    label: 'Analysis',
    title: 'Analyze every workout in depth',
    body: 'Open any session for synced power, heart-rate, pace, cadence and elevation. Drag across the chart to select a segment and read its averages instantly.',
    bullets: [
      'Power + HR + pace on one timeline',
      'Segment stats with one drag',
      'Laps, intervals and best efforts highlighted',
    ],
    videoId: '03-analyze-workout',
    image: '/screenshots/analytics-page.png',
    mediaCaption: 'Deep-dive charts for every uploaded workout',
    cta: 'Open training',
    href: '/training',
    accent: '#06b6d4',
  },
  {
    id: 'power-profile',
    icon: SignalIcon,
    label: 'Power profile',
    title: 'See your power profile & best efforts',
    body: 'LaChart finds your best 5 s sprint, 1-min attack, 5-min VO₂max, 20-min threshold and 60-min endurance power — then jumps you to where you hit them.',
    bullets: [
      'Classic power-duration curve',
      'Tap any point to open that effort',
      'Track progression over the season',
    ],
    videoId: '04-power-profile',
    image: '/images/training-analytics-960.webp',
    mediaCaption: 'Best efforts mapped across durations',
    cta: 'View my profile',
    href: '/training',
    accent: '#7c3aed',
  },
  {
    id: 'lactate-curve',
    icon: ArrowTrendingUpIcon,
    label: 'Lactate testing',
    title: 'Watch your lactate curve evolve',
    body: 'Every new test rebuilds your curve with LT1, LT2, IAT and OBLA thresholds — previous tests overlay so progress is impossible to miss.',
    bullets: [
      'Automatic threshold detection',
      'Compare tests side-by-side',
      'Trend lines for LT1 / LT2 over time',
    ],
    videoId: '05-lactate-curve',
    image: '/images/lactate_curve-960.webp',
    mediaCaption: 'Thresholds update with every test you log',
    cta: 'View my tests',
    href: '/testing',
    accent: '#10b981',
  },
  {
    id: 'training-zones',
    icon: AdjustmentsHorizontalIcon,
    label: 'Zones',
    title: 'Training zones from your lactate',
    body: 'Forget generic HR formulas. Power, pace and heart-rate zones are built directly from your LT1 and LT2 — and refresh after every test.',
    bullets: [
      'Cycling, running & swimming zones',
      'Power, pace and HR in one place',
      'Export or copy zones to your devices',
    ],
    videoId: '06-training-zones',
    image: '/images/zones-generator-960.webp',
    mediaCaption: 'Zones derived from your own physiology',
    cta: 'Check my zones',
    href: '/settings',
    accent: '#0d9488',
  },
  {
    id: 'plan-workout',
    icon: CalendarDaysIcon,
    label: 'Planner',
    title: 'Plan workouts in the calendar',
    body: 'Build structured sessions — warm-up, intervals with target zones, recoveries, cooldown — and drop them onto any day. See planned vs actual side-by-side in your calendar.',
    bullets: [
      'Interval builder with power, HR or pace targets',
      'Save templates and reuse them every week',
      'Planned TSS feeds Form & Fitness projection',
    ],
    videoId: '07-plan-workout',
    image: '/images/ios-launch/gallery/plan-workout.png',
    mediaCaption: 'Build a session, then drop it on any calendar day',
    cta: 'Open the planner',
    href: '/workout-planner',
    accent: '#8b5cf6',
  },
  {
    id: 'live-workout',
    icon: PlayCircleIcon,
    label: 'Live workout',
    title: 'Run workouts live, step-by-step',
    body: 'Open a planned session and execute it with live prompts, target zones and lap timers — on your phone or in the browser.',
    bullets: [
      'Step-by-step interval guidance',
      'Target power / HR / pace per block',
      'Completed session syncs back to the calendar',
    ],
    videoId: '08-live-workout',
    image: '/images/training-calendar-960.webp',
    mediaCaption: 'Follow the plan lap by lap',
    cta: "See today's plan",
    href: '/training-calendar',
    accent: '#0ea5e9',
  },
  {
    id: 'lactate-interval',
    icon: BeakerIcon,
    label: 'Lactate log',
    title: 'Add lactate values to any interval',
    body: 'Tag any interval of an existing workout with a blood-lactate sample. Each sample feeds straight back into your curve and zones.',
    bullets: [
      'Attach mmol/L to a specific lap',
      'Works on Strava, FIT and manual logs',
      'Instant update to threshold model',
    ],
    videoId: '09-lactate-interval',
    image: '/about-design/training-log-page.png',
    mediaCaption: 'Lactate samples tied to real intervals',
    cta: 'Try it',
    href: '/training-calendar',
    accent: '#ef4444',
  },
  {
    id: 'form-fitness',
    icon: HeartIcon,
    label: 'Form & Fitness',
    title: 'Track form, fitness & fatigue',
    body: 'CTL, ATL and TSB charted over weeks so you see when you peak, when you overreach, and when to back off — built from every workout you log.',
    bullets: [
      'Fitness / Fatigue / Form (CTL / ATL / TSB)',
      'Weekly load vs optimal range',
      'Future projection from planned sessions',
    ],
    videoId: '10-form-fitness',
    image: '/images/Form-fitness-chart-960.webp',
    mediaCaption: 'PMC chart synced with your calendar TSS',
    cta: 'See my form',
    href: '/dashboard',
    accent: '#ec4899',
  },
  {
    id: 'compare-tests',
    icon: ChartBarSquareIcon,
    label: 'Compare',
    title: 'Compare sessions & tests side-by-side',
    body: 'Stack any two workouts or lactate tests on one chart — pace, power, HR, lactate — and watch how you look fresh vs fatigued, base vs race-fit.',
    bullets: [
      'Overlay two activities or tests',
      'Same axes for power, HR and lactate',
      'Ideal before/after a training block',
    ],
    videoId: '11-compare-tests',
    image: '/screenshots/lactate-curve-view.png',
    mediaCaption: 'Spot differences between two efforts instantly',
    cta: 'Open compare',
    href: '/training',
    accent: '#0891b2',
  },
  {
    id: 'pdf-branding',
    icon: PaintBrushIcon,
    label: 'Reports',
    title: 'Brand your PDF reports',
    body: 'Upload your logo, set your studio name, address and colour — every test PDF goes out as your own branded handout for athletes.',
    bullets: [
      'Logo, colours and contact details',
      'Full lactate curve + zone tables',
      'One-click send to athlete email',
    ],
    videoId: '12-pdf-branding',
    image: '/about-design/lachart-test-pdf.png',
    mediaCaption: 'Professional PDFs with your studio branding',
    cta: 'Set up branding',
    href: '/settings?tab=branding',
    accent: '#f59e0b',
    coachOnly: true,
  },
  {
    id: 'coach-squad',
    icon: UsersIcon,
    label: 'Coach tools',
    title: 'Manage your whole squad',
    body: 'Invite athletes by email, switch between them in one tap, and track each one’s tests, zones and form from a single coach dashboard.',
    bullets: [
      'Invite & manage unlimited athletes',
      'Switch athlete context in one click',
      'Dashboard, calendar and tests per athlete',
    ],
    videoId: '13-coach-squad',
    image: '/characters/coach-laptop.png',
    mediaCaption: 'One hub for your entire roster',
    cta: 'Open athletes',
    href: '/athletes',
    accent: '#d946ef',
    coachOnly: true,
  },
  {
    id: 'ios-app',
    icon: DevicePhoneMobileIcon,
    label: 'Mobile',
    title: 'LaChart on iPhone & Apple Watch',
    body: 'Take your zones, plans and live workouts anywhere. Start a session on your wrist and it syncs back to LaChart automatically.',
    bullets: [
      'Native iOS app on the App Store',
      'Home-screen Form / Fitness widget',
      'Apple Health sync + push notifications',
    ],
    videoId: '14-ios-app',
    image: '/images/ios-launch/iphone-dashboard.png',
    mediaCaption: 'Dashboard, plans and live workouts on the go',
    cta: 'Get the app',
    href: 'https://apps.apple.com/cz/app/lachart/id6764768876?l=cs',
    accent: '#111827',
  },
];

/** Slides with resolved video URLs (null until WHATS_NEW_VIDEOS_READY[id] is true). */
export const WHATS_NEW_SLIDES = RAW_SLIDES.map((slide) => ({
  ...slide,
  video: whatsNewVideoUrl(slide.videoId),
}));
