// Blog posts metadata — add new posts here, full content in individual files
export const blogPosts = [
  {
    slug: 'how-lachart-calculates-lt1-lt2',
    title: 'How LaChart Calculates LT1 and LT2: The Science Behind the Algorithm',
    excerpt: 'An in-depth look at the 8 threshold detection methods LaChart uses — from D-max and OBLA to log-log transformation — and how they are combined to produce accurate, reproducible lactate thresholds.',
    date: '2025-01-20',
    readTime: '12 min',
    category: 'Science & Technology',
    tags: ['LT1', 'LT2', 'algorithm', 'OBLA', 'D-max', 'lactate threshold'],
    image: '/blog/lachart-algorithm.png',
    featured: true,
  },
  {
    slug: 'lactate-testing-protocol-guide',
    title: 'The Complete Blood Lactate Testing Protocol: Step-by-Step Guide for Athletes and Coaches',
    excerpt: 'Everything you need to know to run a valid lactate threshold test — warm-up duration, step length, sampling technique, and how to avoid the most common errors that corrupt your data.',
    date: '2025-01-15',
    readTime: '10 min',
    category: 'Testing Protocol',
    tags: ['lactate test', 'protocol', 'blood sampling', 'coaches', 'athletes'],
    image: '/blog/lactate-protocol.png',
    featured: true,
  },
  {
    slug: 'lt1-vs-lt2-training-zones',
    title: 'LT1 vs LT2: What They Mean for Your Training Zones',
    excerpt: 'Most athletes confuse LT1 (aerobic threshold) with LT2 (anaerobic threshold). This article explains the physiological difference, why both matter, and how they translate into practical training zones for cycling, running, and triathlon.',
    date: '2025-01-10',
    readTime: '9 min',
    category: 'Training Science',
    tags: ['LT1', 'LT2', 'training zones', 'Zone 2', 'aerobic threshold'],
    image: '/blog/lt1-lt2-zones.png',
    featured: false,
  },
  {
    slug: 'obla-dmax-iat-methods-compared',
    title: 'OBLA, D-max, IAT, Log-Log: Which Lactate Threshold Method is Most Accurate?',
    excerpt: 'A practical comparison of the four most widely used lactate threshold detection methods, their scientific background, and why no single method is perfect — which is why LaChart uses all of them together.',
    date: '2025-01-05',
    readTime: '11 min',
    category: 'Science & Technology',
    tags: ['OBLA', 'D-max', 'IAT', 'log-log', 'threshold methods'],
    image: '/blog/threshold-methods.png',
    featured: false,
  },
];
