// Blog posts metadata — single source of truth for index cards, related posts, and SEO
export const blogPosts = [
  {
    slug:     'how-lachart-calculates-lt1-lt2',
    title:    'How LaChart Calculates LT1 and LT2: The Science Behind the Algorithm',
    excerpt:  'An in-depth look at the 8 threshold detection methods LaChart uses — from D-max and OBLA to log-log transformation — and how they are combined to produce accurate, reproducible lactate thresholds.',
    date:     '2025-01-20',
    readTime: '12 min',
    category: 'Science & Technology',
    tags:     ['LT1', 'LT2', 'algorithm', 'OBLA', 'D-max', 'lactate threshold'],
    image:    '/images/lactate_curve.jpg',
    featured: true,
  },
  {
    slug:     'lactate-testing-protocol-guide',
    title:    'The Complete Blood Lactate Testing Protocol: Step-by-Step Guide for Athletes and Coaches',
    excerpt:  'Everything you need to know to run a valid lactate threshold test — warm-up duration, step length, sampling technique, and how to avoid the most common errors that corrupt your data.',
    date:     '2025-01-15',
    readTime: '10 min',
    category: 'Testing Protocol',
    tags:     ['lactate test', 'protocol', 'blood sampling', 'coaches', 'athletes'],
    image:    '/images/lactate_testing.png',
    featured: true,
  },
  {
    slug:     'lt1-vs-lt2-training-zones',
    title:    'LT1 vs LT2: What They Mean for Your Training Zones',
    excerpt:  'Most athletes confuse LT1 (aerobic threshold) with LT2 (anaerobic threshold). This article explains the physiological difference, why both matter, and how they translate into practical training zones for cycling, running, and triathlon.',
    date:     '2025-01-10',
    readTime: '9 min',
    category: 'Training Science',
    tags:     ['LT1', 'LT2', 'training zones', 'Zone 2', 'aerobic threshold'],
    image:    '/images/lactate_curve_calculator_lachart.jpg',
    featured: false,
  },
  {
    slug:     'obla-dmax-iat-methods-compared',
    title:    'OBLA, D-max, IAT, Log-Log: Which Lactate Threshold Method is Most Accurate?',
    excerpt:  'A practical comparison of the four most widely used lactate threshold detection methods, their scientific background, and why no single method is perfect — which is why LaChart uses all of them together.',
    date:     '2025-01-05',
    readTime: '11 min',
    category: 'Science & Technology',
    tags:     ['OBLA', 'D-max', 'IAT', 'log-log', 'threshold methods'],
    image:    '/images/lactate-analysis.jpg',
    featured: false,
  },
  {
    slug:     'lactate-test-at-home',
    title:    'How to Do a Lactate Threshold Test at Home: A No-Lab Guide for Cyclists and Runners',
    excerpt:  'A practical, equipment-only-needed guide to running your first blood-lactate test at home — what analyzer to buy, how to set up the step protocol, where to prick, and how to avoid the four most common rookie mistakes.',
    date:     '2026-05-17',
    readTime: '14 min',
    category: 'Testing Protocol',
    tags:     ['lactate test', 'home lab', 'DIY', 'lactate analyzer', 'cycling', 'running'],
    image:    '/images/lactate_testing.png',
    featured: true,
  },
  {
    slug:     'lactate-test-interpretation',
    title:    'Reading Your Lactate Test Step by Step: From Raw Numbers to Training Zones',
    excerpt:  'Got a lactate test result on your screen but no clue what it means? Here is a stage-by-stage walkthrough — how to spot the LT1 inflection, the LT2 deflection, the curve shape clues, and the red flags that mean re-test.',
    date:     '2026-05-17',
    readTime: '11 min',
    category: 'Training Science',
    tags:     ['lactate curve', 'interpretation', 'LT1', 'LT2', 'training zones'],
    image:    '/images/lactate_curve.jpg',
    featured: true,
  },
  {
    slug:     'ftp-vs-lt2',
    title:    'FTP vs LT2: Are They the Same Power? Spoiler — Usually Yes, Sometimes No',
    excerpt:  'FTP is everywhere in cycling, LT2 is the gold standard in physiology. They sit next to each other on the curve but they are not identical — here is exactly how much they differ, when they line up, and which one you should actually train against.',
    date:     '2026-05-17',
    readTime: '10 min',
    category: 'Training Science',
    tags:     ['FTP', 'LT2', 'lactate threshold', 'cycling', 'training zones'],
    image:    '/images/lactate_curve_calculator_lachart.jpg',
    featured: false,
  },
];
